<!DOCTYPE html>
<html lang="fr-CA">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hugo Nadeau - mon blogue de programmation</title>

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link href="css/output.css" rel="stylesheet">
    <link href="css/styles.css" rel="stylesheet">
    <link href="css/mes-styles.css" rel="stylesheet">
</head>
<body>
<header class="fixed w-full">
    <nav class="bg-white border-gray-200 py-2.5 dark:bg-gray-900">
        <div class="flex flex-wrap items-center justify-between max-w-screen-xl px-4 mx-auto">
            <a href="#" class="flex items-center couleur">
                <img src="./images/logo.svg" class="couleur h-6 mr-3 sm:h-9" alt="Landwind Logo">
                <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white couleur">Hugo Nadeau</span>
            </a>
            <nav class="menuprincipal">
                <div class="menumobile">
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
                <ul>
                    <li class="actif couleur" ><a href="index.html">Accueil</a></li>
                    <li><a href="../categorie-php.php">PHP</a></li>
                    <li><a href="../categorie-swiftui.php">SwiftUI</a></li>
                    <li><a href="../categorie-javascript.php">JavaScript</a></li>
                    <li><a href="../categorie-autres.php">Autres</a></li>
                </ul>
            </nav>
        </div>
    </nav>
</header>