<footer class="bg-white dark:bg-gray-800">
    <div class="max-w-screen-xl p-4 py-6 mx-auto lg:py-16 md:p-8 lg:p-10">
        <div class="text-center">
            <a href="#"
               class="flex items-center justify-center mb-5 text-2xl font-semibold text-gray-900 dark:text-white">
                <img src="./images/logo.svg" class="couleur h-6 mr-3 sm:h-9" alt="Landwind Logo">
                Landwind
            </a>
            <span class="block text-sm text-center text-gray-500 dark:text-gray-400">© Hugo Nadeau. Tous droits réservés. Propulsé par <a
                    href="https://flowbite.com" class="couleur hover:underline">Flowbite</a> et <a
                    href="https://tailwindcss.com" class="couleur hover:underline">Tailwind CSS</a>.
                </span>
        </div>
    </div>
</footer>
</body>
</html>