<?php
/**
 * @author  <christiane.lagace@hotmail.com>
 * user: hugon
 * date: 2024-01-23
 * Time: 16:18
 */
?>
<!DOCTYPE html>
<html lang="fr-CA">
<head>
    <title>NadeauHugo-Scores</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="..." />
    <meta name="author" content="...">
    <link rel="icon" href="favicon.ico" />
    <link rel="apple-touch-icon" href="apple-touch-icon.png"/>
    <link rel="stylesheet" href="css/vendor.css">
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="css/ajustements.css">
    <link rel="stylesheet" href="css/mes-styles.css">
    <script src="https://kit.fontawesome.com/7a3ae742a8.js" crossorigin="anonymous"></script></head>
<body id="top">

<!-- page wrap
================================================== -->
<div class="s-pagewrap">

    <!-- # site header
    ================================================== -->
    <header class="couleur1 fixe s-header">

        <div class="s-header__block">
            <div class="s-header__branding">
                <p class="site-title">
                    <a href="index.php" rel="home">Scores</a>
                </p>
                <p class="sous-titre">La plateforme incontournable pour suivre les exploits des joueurs !<sup> <a href="#nbp1">1</a></sup></p>
            </div>
            <a class="s-header__menu-toggle" href="#"><span>Menu</span></a>
        </div> <!-- end s-header__block -->

        <div class="row s-header__nav-wrap couleur1">
            <nav class="s-header__nav">
                <ul>
                    <li class="actif"><a href="#">Jeux</a></li>
                    <li><a href="#">Joueurs</a></li>
                    <li><a href="#">Scores</a></li>
                    <li><a href="a-propos.php">À propos</a></li>
                    <li><a href="calendrier.php">Calendrier</a></li>
                </ul>
            </nav> <!-- end s-header__nav -->
        </div> <!-- end s-header__nav-wrap -->

    </header> <!-- end s-header -->