<!-- # site footer -->
<footer id="colophon" class="couleur4 s-footer">

    <div class="row s-footer__bottom">
        <div class="column ss-copyright">
            <p>Maquette par <a href="https://www.styleshout.com/">StyleShout</a>, 2022</p>
            <p>Site Web par trt5thht, <?php echo date("Y"); ?></p>
            <p id="nbp1">1. Slogan généré par OpenAI. (2023). ChatGPT (version 30 novembre 2022) [Modèle massif de
                langage]. <a href="https://chat.openai.com/chat" target="_blank">https://chat.openai.com/chat</a></p>
        </div>
    </div> <!-- end s-footer__bottom-->

</footer> <!-- end s-footer -->

</div> <!-- end s-pagewrap -->

</body>
</html>